library(rworldmap)
library(dplyr)
library(RColorBrewer)
rainfallData <- read.csv("WorldRainfall.csv")
annualRainfall <- data.frame(rainfallData %>% group_by(rainfallData$ISO3, rainfallData$Year) %>% summarise_each(funs(mean), RainfallMM))
colnames(annualRainfall) <- c("ISOCode", "Year", "Rainfall")
annualRainfall$ISOCode <- trimws(annualRainfall$ISOCode , which = c("left"))
colourPalette <- RColorBrewer::brewer.pal(7, 'BuPu')
### 1991 ###
annualRainfall1991 <- subset(annualRainfall , Year == 1991)
mappedRainfall1991 <- joinCountryData2Map(annualRainfall1991, joinCode = "ISO3", nameJoinColumn = "ISOCode")
par(mai=c(0,0,0.2,0),xaxs="i",yaxs="i")
tiff("graphs/maps/rainfall1991.tiff", units="in", width=8, height=6, res=400)
mapCountryData(mappedRainfall1991, nameColumnToPlot = "Rainfall" , mapTitle = "Average Global Rainfall 1991 (mm)", colourPalette = colourPalette)
dev.off()
### 1991 ###
annualRainfall1997 <- subset(annualRainfall , Year == 1997)
mappedRainfall1997 <- joinCountryData2Map(annualRainfall1997, joinCode = "ISO3", nameJoinColumn = "ISOCode")
par(mai=c(0,0,0.2,0),xaxs="i",yaxs="i")
tiff("graphs/maps/rainfall1997.tiff", units="in", width=8, height=6, res=400)
mapCountryData(mappedRainfall1997, nameColumnToPlot = "Rainfall" , mapTitle = "Average Global Rainfall 1997 (mm)", colourPalette = colourPalette)
dev.off()
### 1991 ###
annualRainfall2004 <- subset(annualRainfall , Year == 2004)
mappedRainfall2004 <- joinCountryData2Map(annualRainfall2004, joinCode = "ISO3", nameJoinColumn = "ISOCode")
par(mai=c(0,0,0.2,0),xaxs="i",yaxs="i")
tiff("graphs/maps/rainfall2004.tiff", units="in", width=8, height=6, res=400)
mapCountryData(mappedRainfall2004, nameColumnToPlot = "Rainfall" , mapTitle = "Average Global Rainfall 2004 (mm)", colourPalette = colourPalette)
dev.off()
### 2010 ###
annualRainfall2010 <- subset(annualRainfall , Year == 2010)
mappedRainfall2010 <- joinCountryData2Map(annualRainfall2010, joinCode = "ISO3", nameJoinColumn = "ISOCode")
par(mai=c(0,0,0.2,0),xaxs="i",yaxs="i")
tiff("graphs/maps/rainfall2010.tiff", units="in", width=8, height=6, res=400)
mapCountryData(mappedRainfall2010, nameColumnToPlot = "Rainfall" , mapTitle = "Average Global Rainfall 2010 (mm)", colourPalette = colourPalette)
dev.off()
### Comparison ###
tiff("graphs/maps/rain_comparison.tiff", units="in", width=8, height=6, res=400)
op <- par(fin=c(7,9),mfcol=c(2,2),mai=c(0,0,0.2,0),xaxs="i",yaxs="i")
g1 <- mapCountryData(mappedRainfall1991, nameColumnToPlot = "Rainfall" , mapTitle = "Global Rainfall 1991", colourPalette = colourPalette, addLegend=FALSE)
do.call(addMapLegend, c(g1, horizontal=FALSE, legendWidth=0.7, legendLabels="none"))
g2 <- mapCountryData(mappedRainfall1997, nameColumnToPlot = "Rainfall" , mapTitle = "Global Rainfall 1997", colourPalette = colourPalette, addLegend=FALSE)
do.call(addMapLegend, c(g2, horizontal=FALSE, legendWidth=0.7, legendLabels="none"))
g3 <- mapCountryData(mappedRainfall2004, nameColumnToPlot = "Rainfall" , mapTitle = "Global Rainfall 2004", colourPalette = colourPalette, addLegend=FALSE)
do.call(addMapLegend, c(g3, horizontal=FALSE, legendWidth=0.7, legendLabels="none"))
g4 <- mapCountryData(mappedRainfall2010, nameColumnToPlot = "Rainfall" , mapTitle = "Global Rainfall 2010", colourPalette = colourPalette, addLegend=FALSE)
do.call(addMapLegend, c(g4, horizontal=FALSE, legendWidth=0.7, legendLabels="none"))
dev.off()