library(rworldmap)
library(dplyr)
temperatureData <- read.csv("WorldTemperature.csv")
annualTemperature <- data.frame(temperatureData %>% group_by(temperatureData$ISO3, temperatureData$Year) %>% summarise_each(funs(mean),TemperatureCelsius))
colnames(annualTemperature) <- c("ISOCode", "Year", "Temperature Celsius")
annualTemperature$ISOCode <- trimws(annualTemperature$ISOCode , which = c("left"))
### 1991 ###
annualTemperature1991 <- subset(annualTemperature , Year == 1991)
mappedTemperature1991 <- joinCountryData2Map(annualTemperature1991, joinCode = "ISO3", nameJoinColumn = "ISOCode")
par(mai=c(0,0,0.2,0),xaxs="i",yaxs="i")
png("graphs/maps/temperature1991.png")
temperatureGraph1991 <- mapCountryData(mappedTemperature1991, nameColumnToPlot = "Temperature Celsius" , mapTitle = "Average Global Temperature 1991 (celsius)")
dev.off()
### 1997 ###
annualTemperature1997 <- subset(annualTemperature , Year == 1997)
mappedTemperature1997 <- joinCountryData2Map(annualTemperature1997, joinCode = "ISO3", nameJoinColumn = "ISOCode")
par(mai=c(0,0,0.2,0),xaxs="i",yaxs="i")
png("graphs/maps/temperature1997.png")
temperatureGraph1997 <- mapCountryData(mappedTemperature1997, nameColumnToPlot = "Temperature Celsius" , mapTitle = "Average Global Temperature 1997 (celsius)")
dev.off()
### 2004 ###
annualTemperature2004 <- subset(annualTemperature , Year == 2004)
mappedTemperature2004 <- joinCountryData2Map(annualTemperature2004, joinCode = "ISO3", nameJoinColumn = "ISOCode")
par(mai=c(0,0,0.2,0),xaxs="i",yaxs="i")
png("graphs/maps/temperature2004.png")
temperatureGraph2004 <- mapCountryData(mappedTemperature2004, nameColumnToPlot = "Temperature Celsius" , mapTitle = "Average Global Temperature 2004 (celsius)")
dev.off()
### 2010 ###
annualTemperature2010 <- subset(annualTemperature , Year == 2010)
mappedTemperature2010 <- joinCountryData2Map(annualTemperature2010, joinCode = "ISO3", nameJoinColumn = "ISOCode")
par(mai=c(0,0,0.2,0),xaxs="i",yaxs="i")
png("graphs/maps/temperature2010.png")
temperatureGraph2010 <- mapCountryData(mappedTemperature2010, nameColumnToPlot = "Temperature Celsius" , mapTitle = "Average Global Temperature 2010 (celsius)")
dev.off()
### Comparison ###
png("graphs/maps/temp_comparison.png")
op <- par(fin=c(7,9),mfcol=c(2,2),mai=c(0,0,0.2,0),xaxs="i",yaxs="i")
g1 <- mapCountryData(mappedTemperature1991, nameColumnToPlot = "Temperature Celsius" , mapTitle = "Global Temperature 1991", addLegend=FALSE)
do.call(addMapLegend, c(g1, horizontal=FALSE, legendWidth=0.7, legendLabels="none"))
g2 <- mapCountryData(mappedTemperature1997, nameColumnToPlot = "Temperature Celsius" , mapTitle = "Global Temperature 1997", addLegend=FALSE)
do.call(addMapLegend, c(g1, horizontal=FALSE, legendWidth=0.7, legendLabels="none"))
g3 <- mapCountryData(mappedTemperature2004, nameColumnToPlot = "Temperature Celsius" , mapTitle = "Global Temperature 2004", addLegend=FALSE)
do.call(addMapLegend, c(g1, horizontal=FALSE, legendWidth=0.7, legendLabels="none"))
g4 <- mapCountryData(mappedTemperature2010, nameColumnToPlot = "Temperature Celsius" , mapTitle = "Global Temperature 2010", addLegend=FALSE)
do.call(addMapLegend, c(g1, horizontal=FALSE, legendWidth=0.7, legendLabels="none"))
dev.off()
